# Book settings
title: Understanding Neural Networks
author: Dominick DeCanio (dcd9ce@virginia.edu)
#logo: surf.jpg
#repository:
#  url: https://github.com/surfing-the-data-pipeline
#  branch: main
#html:
#  use_repository_button: true
#  use_issues_button: true
#  use_edit_page_button: true
#launch_buttons:
#  notebook_interface: "jupyterlab"
#  binderhub_url: "https://mybinder.org/v2/gh/jkropko/surfing-the-data-pipeline/main"
#  colab_url: "https://colab.research.google.com"
latex:
  latex_documents:
    targetname: book.tex